OrderingSystem/Controllers/MenuController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OrderingSystem.Models;
using OrderingSystem.Services;
using OrderingSystem.ViewModels;

namespace OrderingSystem.Controllers
{
    public class MenuController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;
        private readonly ICartService _cartService;

        public MenuController(ICategoryService categoryService, IProductService productService, ICartService cartService)
        {
            _categoryService = categoryService;
            _productService = productService;
            _cartService = cartService;
        }

        public async Task<IActionResult> Index(int? categoryId)
        {
            var model = new ProductCategoryViewModel
            {
                categories = await _categoryService.GetCategoriesAsync(),
                products = await _productService.GetProductsAsync(categoryId),
                SelectedCategoryId = categoryId
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetProductVariants(int productId)
        {
            var product = await _productService.GetByIdWithVariantsAsync(productId); // You may implement this if not available
            if (product == null) return NotFound();

            return Json(product.Variants.Select(v => new
            {
                id = v.Id,
                variantName = v.VariantName,
                description = v.Description,
                price = v.Price
            }));
        }




    }
}

OrderingSystem/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OrderingSystem.Services;
using OrderingSystem.ViewModels;

namespace OrderingSystem.Controllers
{

    
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        [HttpGet]
        public async Task<IActionResult> GetOrderItems(int orderId)
        {
            var order = await _orderService.GetOrderItemById(orderId);
            if (order == null) return NotFound();

            return Json(order.OrderItems);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index(string status = "All")
        {
            var orders = await _orderService.GetAllOrders(status);

            
            return View(orders);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateStatus(int OrderId, string newStatus)
        {

            await _orderService.UpdateDeliveryStatus(OrderId, newStatus);
            TempData["Success"] = "Order status updated successfully.";

            return RedirectToAction("Index");
        }

       

    }
}

OrderingSystem/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OrderingSystem</title>
    <link rel="stylesheet" href="~/css/AdminSidebar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/OrderingSystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>
<body>
    <aside class="sidebar">
        <nav class="sidebar-nav ">
            <h4 class="text-center mb-4">Admin Panel</h4>

            <ul class="nav-list primary-nav">

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
                        <span class="material-symbols-outlined">Dashboard</span>
                        <span class="nav-label">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Product" asp-action="Index">
                        <span class="material-symbols-outlined">package_2</span>
                        <span class="nav-label">Product</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Category" asp-action="Index">
                        <span class="material-symbols-outlined">category</span>
                        <span class="nav-label">Category</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Order" asp-action="Index">
                        <span class="material-symbols-outlined">list_alt</span>
                        <span class="nav-label">Order List</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a asp-controller="Account" asp-action="Index" class="nav-link">
                        <span class="material-symbols-outlined"> manage_accounts</span>
                        <span class="nav-label">Account</span>
                    </a>

                </li>

                <li class="nav-item dropdown-container">
                    <a href="#" class="nav-link" data-bs-toggle="collapse" data-bs-target="#officialMenu">
                        <span class="material-symbols-outlined"> Settings</span>
                        <span class="nav-label">Settings</span>
                        <span class="dropdown-icon material-symbols-outlined">
                            keyboard_arrow_down
                        </span>
                    </a>
                    <ul class="dropdown_menu collapse" id="officialMenu">
                        <li class="nav-item">
                            <a class="nav-link dropdown-link" asp-controller="Official" asp-action="Index">
                                Officials
                            </a>
                        </li>
                        @* <li class="nav-item">
                        <a class="nav-link dropdown-link" asp-controller="Settings" asp-action="Register">
                        Change Password
                        </a>
                        </li> *@
                    </ul>
                </li>

            </ul>
            <ul class="nav-list secondary-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Account" asp-action="Logout">
                        <span class="material-symbols-outlined">logout</span>
                        <span class="nav-label">Logout</span>
                    </a>
                </li>
            </ul>
        </nav>
    </aside>
    <header>
        <nav>
            <p>NIKKO VILLANUEVA</p>
        </nav>
    </header>
    <div>
        <main>
            @RenderBody()
        </main>
    </div>

    @*  <footer class="bg-dark text-white py-4 mt-5">
    <div class="container">
    &copy; 2025 - OrderingSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/autonumeric@4.6.0/dist/autoNumeric.min.js"></script>
    <script src="~/js/category.js" asp-append-version="true"></script>
    <script src="~/js/product.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OrderingSystem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<User> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Dolce Misu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/cart.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OrderingSystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>
<body class="d-flex flex-column min-vh-100">

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark px-2 py-2" style="background-color: #460C61;">
        <div class="container-fluid gap-2">
            <!-- Toggler -->
            <button class="navbar-toggler ms-2 order-lg-1" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
                    aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Brand -->
            <a class="navbar-brand fw-bold text-warning me-auto" asp-controller="Home" asp-action="Index">Dolce Misu</a>

            <!-- Collapsible Nav Links -->
            <div class="collapse navbar-collapse order-lg-1" id="navbarContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link fw-semibold" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fw-semibold" asp-controller="Menu" asp-action="Index">Menu</a>
                    </li>
                </ul>
            </div>


            <div class="d-flex align-items-center gap-3 order-lg-3 ms-auto">

                <a class="nav-link position-relative text-white p-0" asp-controller="Cart" asp-action="Index">
                    <i class="bi bi-cart fs-5"></i>
                    <span id="cart-count">
                        @await Component.InvokeAsync("CartCount")
                    </span>
                </a>

                @if (signInManager.IsSignedIn(User))
                {
                    var username = User.Identity?.Name;
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white d-flex align-items-center" href="#" id="userDropdown"
                           role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person-circle me-1"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="userDropdown">
                            <li><a class="dropdown-item" asp-controller="Account" asp-action="Profile">View Account</a></li>
                            <li><a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a></li>
                        </ul>
                    </div>
                }
                else
                {
                    <a class="btn btn-sm btn-outline-warning fw-bold" asp-controller="Account" asp-action="Login">Sign in</a>
                }

            </div>
        </div>

    </nav>




    <main role="main" class="flex-fill">
        @RenderBody()
    </main>

    <footer class="py-4" style="background-color: #FFFBF4">
        <div class="container d-flex flex-column flex-md-row justify-content-between align-items-start">
            <div class="mb-3 mb-md-0">
                <h5 style="color: #E933F6">Dolce Misu</h5>
                <p class="mb-1 text-dark-50"><i class="bi bi-telephone"> 09369139733 </i></p>
                <p class="text-dark-50"><i class="bi bi-envelope"> dolceMisu@gmail.com</i></p>
            </div>
            <div class="text-md-end">
                <h5 class="text-dark">Follow Us</h5>
                <div class="footer-social d-flex justify-content-center align-items-center gap-2">
                    <a href="#" class="text-dark"><i class="bi bi-instagram"></i></a>
                    <a href="#" class="text-dark"><i class="bi bi-facebook"></i></a>
                    <a href="#" class="text-dark"><i class="bi bi-tiktok"></i></a>
                </div>
            </div>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/cart.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OrderingSystem/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Dolce Misu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OrderingSystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>
<body>

   
    <main role="main">
        @RenderBody()
    </main>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/login.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>